#%RAML 1.0
title: My super cool, example API
version: v1
baseUri: http://{environment}.api.domain.com/{version}/
mediaType: [ application/json, application/xml ]

baseUriParameters:
  environment:
    type: string
    description: |
      API environment. The value can be one of "development", "stage" or "production"
    pattern: (development|stage|production)
    example: production
documentation:
  - title: Read this!
    content: |
      # This is an example API spec
      The API doesn't exists in the real world therefore calls made to any endpoint will always fail.\
  - title: Test docs
    content: |
      # A test documentation.
      This text was created by ARC's RAML editor.
types:
  ErrorResource:
    description: A response that is errored
    type: object
    properties:
      error:
        type: boolean
        required: true
        example: true
        default: true
        description: Indicate that the response is errored.
      message:
        type: string
        description: The error message associated with the error.
        example: <<example>>
        required: true
  Feature:
    description: A feature to test enum values in the URI parameters.
    type: string
    enum:
        - A
        - B
        - C
/test-parameters/{feature}:
  uriParameters:
    feature:
      type: string
      enum:
        - A
        - B
        - C
  get:
    description: To test enum values in the URI parameters for inline type declaration.
  /{typeFeature}:
    uriParameters:
      typeFeature:
        type: Feature
    get:
      description: To test enum values in the URI parameters for global type declaration.
